2024-09-22 19:07:41,259 INFO    StreamThr :10259 [internal.py:wandb_internal():85] W&B internal server running at pid: 10259, started at: 2024-09-22 19:07:41.258652
2024-09-22 19:07:41,264 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status
2024-09-22 19:07:41,270 INFO    WriterThread:10259 [datastore.py:open_for_write():87] open: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/run-eobel7kq.wandb
2024-09-22 19:07:41,271 DEBUG   SenderThread:10259 [sender.py:send():391] send: header
2024-09-22 19:07:41,311 DEBUG   SenderThread:10259 [sender.py:send():391] send: run
2024-09-22 19:07:42,006 INFO    SenderThread:10259 [dir_watcher.py:__init__():211] watching files in: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files
2024-09-22 19:07:42,006 INFO    SenderThread:10259 [sender.py:_start_run_threads():1200] run started: eobel7kq with start time 1727021261.259422
2024-09-22 19:07:42,018 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: run_start
2024-09-22 19:07:42,019 DEBUG   HandlerThread:10259 [system_info.py:__init__():26] System info init
2024-09-22 19:07:42,019 DEBUG   HandlerThread:10259 [system_info.py:__init__():41] System info init done
2024-09-22 19:07:42,019 INFO    HandlerThread:10259 [system_monitor.py:start():194] Starting system monitor
2024-09-22 19:07:42,020 INFO    SystemMonitor:10259 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-22 19:07:42,020 INFO    HandlerThread:10259 [system_monitor.py:probe():214] Collecting system info
2024-09-22 19:07:42,020 INFO    SystemMonitor:10259 [interfaces.py:start():188] Started cpu monitoring
2024-09-22 19:07:42,021 INFO    SystemMonitor:10259 [interfaces.py:start():188] Started disk monitoring
2024-09-22 19:07:42,021 INFO    SystemMonitor:10259 [interfaces.py:start():188] Started memory monitoring
2024-09-22 19:07:42,023 INFO    SystemMonitor:10259 [interfaces.py:start():188] Started network monitoring
2024-09-22 19:07:42,045 DEBUG   HandlerThread:10259 [system_info.py:probe():152] Probing system
2024-09-22 19:07:42,047 DEBUG   HandlerThread:10259 [system_info.py:_probe_git():137] Probing git
2024-09-22 19:07:42,053 DEBUG   HandlerThread:10259 [system_info.py:_probe_git():145] Probing git done
2024-09-22 19:07:42,053 DEBUG   HandlerThread:10259 [system_info.py:probe():200] Probing system done
2024-09-22 19:07:42,053 DEBUG   HandlerThread:10259 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-88-generic-x86_64-with-glibc2.35', 'python': '3.11.5', 'heartbeatAt': '2024-09-22T16:07:42.045714', 'startedAt': '2024-09-22T16:07:41.252783', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'main.ipynb', 'codePathLocal': 'main.ipynb', 'root': '/home/egor/desktop/tmp/precondnn', 'git': {'remote': 'git@github.com:e1vanov/precondnn.git', 'commit': 'd983a7a1a5cacd34dc089d0132b8c04c04a13c1a'}, 'email': 's02210401@gse.cs.msu.ru', 'host': 'egor-MacBookAir', 'username': 'egor', 'executable': '/home/egor/miniconda3/bin/python', 'cpu_count': 2, 'cpu_count_logical': 4, 'cpu_freq': {'current': 2.46075, 'min': 500.0, 'max': 2900.0}, 'cpu_freq_per_core': [{'current': 2.9, 'min': 500.0, 'max': 2900.0}, {'current': 2.9, 'min': 500.0, 'max': 2900.0}, {'current': 2.234, 'min': 500.0, 'max': 2900.0}, {'current': 2.9, 'min': 500.0, 'max': 2900.0}], 'disk': {'/': {'total': 457.2810821533203, 'used': 57.40239715576172}}, 'memory': {'total': 7.656707763671875}}
2024-09-22 19:07:42,053 INFO    HandlerThread:10259 [system_monitor.py:probe():224] Finished collecting system info
2024-09-22 19:07:42,053 INFO    HandlerThread:10259 [system_monitor.py:probe():227] Publishing system info
2024-09-22 19:07:42,053 DEBUG   HandlerThread:10259 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-09-22 19:07:43,007 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_created():271] file/dir created: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/conda-environment.yaml
2024-09-22 19:07:46,007 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/conda-environment.yaml
2024-09-22 19:07:46,025 DEBUG   HandlerThread:10259 [system_info.py:_save_conda():224] Saving conda packages done
2024-09-22 19:07:46,026 INFO    HandlerThread:10259 [system_monitor.py:probe():229] Finished publishing system info
2024-09-22 19:07:46,030 DEBUG   SenderThread:10259 [sender.py:send():391] send: files
2024-09-22 19:07:46,030 INFO    SenderThread:10259 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-09-22 19:07:46,188 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: python_packages
2024-09-22 19:07:46,189 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: python_packages
2024-09-22 19:07:46,189 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:07:46,190 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:07:46,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:07:46,544 DEBUG   SenderThread:10259 [sender.py:send():391] send: telemetry
2024-09-22 19:07:46,544 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:07:46,736 INFO    wandb-upload_0:10259 [upload_job.py:push():130] Uploaded file /tmp/tmpwxw2s9r3wandb/zj5ob0ld-wandb-metadata.json
2024-09-22 19:07:47,008 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_created():271] file/dir created: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/output.log
2024-09-22 19:07:47,008 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_created():271] file/dir created: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/wandb-metadata.json
2024-09-22 19:07:47,008 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_created():271] file/dir created: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/requirements.txt
2024-09-22 19:07:47,184 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: pause
2024-09-22 19:07:47,184 INFO    HandlerThread:10259 [handler.py:handle_request_pause():728] stopping system metrics thread
2024-09-22 19:07:47,184 INFO    HandlerThread:10259 [system_monitor.py:finish():203] Stopping system monitor
2024-09-22 19:07:47,185 DEBUG   SystemMonitor:10259 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-22 19:07:47,185 INFO    HandlerThread:10259 [interfaces.py:finish():200] Joined cpu monitor
2024-09-22 19:07:47,185 DEBUG   SystemMonitor:10259 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-22 19:07:47,185 DEBUG   SystemMonitor:10259 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-22 19:07:47,185 INFO    HandlerThread:10259 [interfaces.py:finish():200] Joined disk monitor
2024-09-22 19:07:47,186 INFO    HandlerThread:10259 [interfaces.py:finish():200] Joined memory monitor
2024-09-22 19:07:47,186 INFO    HandlerThread:10259 [interfaces.py:finish():200] Joined network monitor
2024-09-22 19:07:47,187 DEBUG   SenderThread:10259 [sender.py:send():391] send: stats
2024-09-22 19:07:49,008 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/output.log
2024-09-22 19:07:52,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:07:56,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:07:57,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:01,189 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:08:01,189 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:08:02,664 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:06,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:08:08,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:14,195 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:15,019 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/config.yaml
2024-09-22 19:08:16,189 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:08:16,189 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:08:16,231 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:08:20,407 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:26,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:08:26,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:31,189 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:08:31,189 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:08:31,565 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:36,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:08:37,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:43,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:46,189 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:08:46,190 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:08:46,231 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:08:48,515 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:54,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:08:56,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:09:00,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:01,189 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:09:01,190 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:09:05,466 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:06,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:09:11,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:16,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:09:16,190 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:09:16,231 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:09:16,469 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:22,192 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:26,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:09:28,192 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:31,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:09:31,190 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:09:33,572 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:36,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:09:39,192 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:44,192 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:46,190 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: stop_status
2024-09-22 19:09:46,191 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: stop_status
2024-09-22 19:09:46,231 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:09:49,418 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:55,193 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:56,191 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-22 19:09:59,847 DEBUG   SenderThread:10259 [sender.py:send():391] send: exit
2024-09-22 19:09:59,847 INFO    SenderThread:10259 [sender.py:send_exit():598] handling exit code: 0
2024-09-22 19:09:59,848 INFO    SenderThread:10259 [sender.py:send_exit():600] handling runtime: 5
2024-09-22 19:09:59,848 INFO    SenderThread:10259 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-22 19:09:59,848 INFO    SenderThread:10259 [sender.py:send_exit():606] send defer
2024-09-22 19:09:59,848 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:09:59,849 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 0
2024-09-22 19:09:59,850 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:09:59,850 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 0
2024-09-22 19:09:59,850 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 1
2024-09-22 19:09:59,851 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:09:59,851 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 1
2024-09-22 19:09:59,851 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:09:59,851 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 1
2024-09-22 19:09:59,851 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 2
2024-09-22 19:09:59,851 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:09:59,851 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 2
2024-09-22 19:09:59,851 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:09:59,851 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 2
2024-09-22 19:09:59,852 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 3
2024-09-22 19:09:59,852 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:09:59,852 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 3
2024-09-22 19:09:59,852 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:09:59,852 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 3
2024-09-22 19:09:59,852 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 4
2024-09-22 19:09:59,852 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:09:59,852 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 4
2024-09-22 19:09:59,852 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:09:59,852 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 4
2024-09-22 19:09:59,853 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 5
2024-09-22 19:09:59,853 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:09:59,853 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 5
2024-09-22 19:09:59,853 DEBUG   SenderThread:10259 [sender.py:send():391] send: summary
2024-09-22 19:09:59,853 INFO    SenderThread:10259 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-22 19:09:59,854 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:09:59,854 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 5
2024-09-22 19:09:59,854 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 6
2024-09-22 19:09:59,854 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:09:59,854 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 6
2024-09-22 19:09:59,854 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:09:59,854 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 6
2024-09-22 19:09:59,854 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 7
2024-09-22 19:09:59,854 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: status_report
2024-09-22 19:09:59,854 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:09:59,855 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 7
2024-09-22 19:09:59,855 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:09:59,855 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 7
2024-09-22 19:10:00,021 ERROR   FileStreamThread:10259 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/cmcmsu/loss_choice/eobel7kq/file_stream
NoneType: None
2024-09-22 19:10:00,055 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_created():271] file/dir created: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/wandb-summary.json
2024-09-22 19:10:00,570 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 8
2024-09-22 19:10:00,570 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:10:00,571 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 8
2024-09-22 19:10:00,571 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:10:00,571 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 8
2024-09-22 19:10:00,571 INFO    SenderThread:10259 [job_builder.py:build():443] Attempting to build job artifact
2024-09-22 19:10:00,571 INFO    SenderThread:10259 [job_builder.py:_get_source_type():572] is repo sourced job
2024-09-22 19:10:00,571 INFO    SenderThread:10259 [job_builder.py:_get_program_relpath():590] run is notebook based run
2024-09-22 19:10:00,593 INFO    SenderThread:10259 [job_builder.py:build():548] adding wandb-job metadata file
2024-09-22 19:10:00,629 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 9
2024-09-22 19:10:00,629 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:10:00,629 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 9
2024-09-22 19:10:00,630 DEBUG   SenderThread:10259 [sender.py:send():391] send: artifact
2024-09-22 19:10:00,847 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-22 19:10:01,056 INFO    Thread-12 :10259 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/output.log
2024-09-22 19:10:01,416 ERROR   SenderThread:10259 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-22 19:10:01,416 ERROR   SenderThread:10259 [internal_api.py:execute():350] {"errors":[{"message":"failed to find run loss_choice/eobel7kq","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2024-09-22 19:10:01,416 ERROR   SenderThread:10259 [sender.py:send_artifact():1551] send_artifact: failed for artifact "job/job-git_github.com_e1vanov_precondnn.git_main.ipynb": It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-22 19:10:01,416 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:10:01,416 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 9
2024-09-22 19:10:01,416 INFO    SenderThread:10259 [dir_watcher.py:finish():358] shutting down directory watcher
2024-09-22 19:10:02,057 INFO    SenderThread:10259 [dir_watcher.py:finish():388] scan: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files
2024-09-22 19:10:02,057 INFO    SenderThread:10259 [dir_watcher.py:finish():402] scan save: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/output.log output.log
2024-09-22 19:10:02,057 INFO    SenderThread:10259 [dir_watcher.py:finish():402] scan save: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/wandb-summary.json wandb-summary.json
2024-09-22 19:10:02,058 INFO    SenderThread:10259 [dir_watcher.py:finish():402] scan save: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/config.yaml config.yaml
2024-09-22 19:10:02,064 INFO    SenderThread:10259 [dir_watcher.py:finish():402] scan save: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/requirements.txt requirements.txt
2024-09-22 19:10:02,067 INFO    SenderThread:10259 [dir_watcher.py:finish():402] scan save: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/conda-environment.yaml conda-environment.yaml
2024-09-22 19:10:02,069 INFO    SenderThread:10259 [dir_watcher.py:finish():402] scan save: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/wandb-metadata.json wandb-metadata.json
2024-09-22 19:10:02,071 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 10
2024-09-22 19:10:02,072 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: poll_exit
2024-09-22 19:10:02,072 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:10:02,072 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 10
2024-09-22 19:10:02,072 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:10:02,072 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 10
2024-09-22 19:10:02,072 INFO    SenderThread:10259 [file_pusher.py:finish():169] shutting down file pusher
2024-09-22 19:10:02,227 ERROR   wandb-upload_0:10259 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-22 19:10:02,227 ERROR   wandb-upload_0:10259 [internal_api.py:execute():350] {"errors":[{"message":"run loss_choice/eobel7kq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-22 19:10:02,228 ERROR   Thread-11 (_thread_body):10259 [step_upload.py:_handle_event():144] Failed to upload file: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/output.log
Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
wandb.errors.CommError: [Errno 32] Broken pipe
2024-09-22 19:10:02,232 ERROR   wandb-upload_1:10259 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-22 19:10:02,232 ERROR   wandb-upload_1:10259 [internal_api.py:execute():350] {"errors":[{"message":"run loss_choice/eobel7kq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-22 19:10:02,232 ERROR   Thread-11 (_thread_body):10259 [step_upload.py:_handle_event():144] Failed to upload file: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
wandb.errors.CommError: [Errno 32] Broken pipe
2024-09-22 19:10:02,411 ERROR   wandb-upload_2:10259 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-22 19:10:02,411 ERROR   wandb-upload_2:10259 [internal_api.py:execute():350] {"errors":[{"message":"run loss_choice/eobel7kq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-22 19:10:02,411 ERROR   wandb-upload_3:10259 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-22 19:10:02,411 ERROR   wandb-upload_3:10259 [internal_api.py:execute():350] {"errors":[{"message":"run loss_choice/eobel7kq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-22 19:10:02,412 ERROR   Thread-11 (_thread_body):10259 [step_upload.py:_handle_event():144] Failed to upload file: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/config.yaml
Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
wandb.errors.CommError: [Errno 32] Broken pipe
2024-09-22 19:10:02,415 ERROR   Thread-11 (_thread_body):10259 [step_upload.py:_handle_event():144] Failed to upload file: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/requirements.txt
Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
wandb.errors.CommError: [Errno 32] Broken pipe
2024-09-22 19:10:02,420 ERROR   wandb-upload_4:10259 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-22 19:10:02,420 ERROR   wandb-upload_4:10259 [internal_api.py:execute():350] {"errors":[{"message":"run loss_choice/eobel7kq not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-22 19:10:02,421 ERROR   Thread-11 (_thread_body):10259 [step_upload.py:_handle_event():144] Failed to upload file: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 352, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
wandb.errors.CommError: [Errno 32] Broken pipe
2024-09-22 19:10:02,624 INFO    Thread-11 (_thread_body):10259 [sender.py:transition_state():626] send defer: 11
2024-09-22 19:10:02,626 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:10:02,626 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 11
2024-09-22 19:10:02,627 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:10:02,627 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 11
2024-09-22 19:10:02,627 INFO    SenderThread:10259 [file_pusher.py:join():175] waiting for file pusher
2024-09-22 19:10:02,627 INFO    SenderThread:10259 [sender.py:transition_state():626] send defer: 12
2024-09-22 19:10:02,628 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: defer
2024-09-22 19:10:02,628 INFO    HandlerThread:10259 [handler.py:handle_request_defer():184] handle defer: 12
2024-09-22 19:10:02,629 DEBUG   SenderThread:10259 [sender.py:send_request():418] send_request: defer
2024-09-22 19:10:02,629 INFO    SenderThread:10259 [sender.py:send_request_defer():622] handle sender defer: 12
2024-09-22 19:10:02,629 INFO    SenderThread:10259 [file_stream.py:finish():601] file stream finish called
2024-09-22 19:10:02,796 ERROR   FileStreamThread:10259 [file_stream.py:_thread_except_body():500] generic exception in filestream thread
Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 496, in _thread_except_body
    self._thread_body()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 452, in _thread_body
    success = self._send(ready_chunks, uploaded=uploaded)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 541, in _send
    self._handle_response(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 507, in _handle_response
    wandb.termerror(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2024-09-22 19:10:02,848 DEBUG   HandlerThread:10259 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-22 19:10:02,947 INFO    SenderThread:10259 [file_stream.py:finish():605] file stream finish is done
2024-09-22 19:10:02,947 ERROR   SenderThread:10259 [file_stream.py:finish():607] FileStream exception
Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 496, in _thread_except_body
    self._thread_body()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 452, in _thread_body
    success = self._send(ready_chunks, uploaded=uploaded)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 541, in _send
    self._handle_response(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 507, in _handle_response
    wandb.termerror(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2024-09-22 19:10:03,849 INFO    HandlerThread:10259 [handler.py:finish():884] shutting down handler
2024-09-22 19:10:03,849 INFO    WriterThread:10259 [datastore.py:close():296] close: /home/egor/desktop/tmp/precondnn/loss_choice_exp/wandb/run-20240922_190741-eobel7kq/run-eobel7kq.wandb
2024-09-22 19:10:03,849 ERROR   StreamThr :10259 [internal.py:wandb_internal():173] Thread SenderThread:
Traceback (most recent call last):
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal.py", line 327, in _process
    self._sm.send(record)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 398, in send
    send_handler(record)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 420, in send_request
    send_handler(record)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 677, in send_request_defer
    self._fs.finish(self._exit_code)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 610, in finish
    raise self._exc_info[1].with_traceback(self._exc_info[2])
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 496, in _thread_except_body
    self._thread_body()
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 452, in _thread_body
    success = self._send(ready_chunks, uploaded=uploaded)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 541, in _send
    self._handle_response(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/file_stream.py", line 507, in _handle_response
    wandb.termerror(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/home/egor/miniconda3/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/egor/miniconda3/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
